POST http://localhost:3001/api/post-reactions
Content-Type: application/json
Authorization: Bearer <token>

{
  "postId": "<id>",
  "reaction": "😀"
}
###

DELETE http://localhost:3001/api/post-reactions
Content-Type: application/json
Authorization: Bearer <token>

{
  "postId": "<id>",
  "reaction": "😀"
}
