# Before sending you need to get a user token.
# Send a POST request from user.http file and copy
# the token value from response (without quotes).

POST http://localhost:3001/api/workspaces
Content-Type: application/json
Authorization: Bearer <insert token here>

{
  "name": "test workspace"
}
###

POST http://localhost:3001/api/workspaces/<:id>/invite
Content-Type: application/json
Authorization: Bearer <insert token here>

{
  "email": "test@gmail.com"
}
