export enum ClientSockets {
  AddPost = 'addPost',
  EditPost = 'editPost',
  DeletePost = 'deletePost',
  EditComment = 'editComment',
  DeleteComment = 'deleteComment',
  JoinChat = 'joinChat',
  LeaveChat = 'leaveChat',
  AddReply = 'addReply',
  AddReaction = 'addReaction',
  DeleteReaction = 'deleteReaction',
  NewUserNotification = 'newUserNotification',
  UpsertDraftPost = 'upsertDraftPost',
  DeleteDraftPost = 'deleteDraftPost',
  UpsertDraftComment = 'upsertDraftComment',
  DeleteDraftComment = 'deleteDraftComment',
  NotifyAndMarkAsUnread = 'notifyAndMarkAsUnread',
  SetChatMuted = 'setChatMuted',
  MarkAsUnreadComment = 'markAsUnreadComment'
}
